ALTER TABLE posts ADD COLUMN publication_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD COLUMN modification_date TIMESTAMP DEFAULT NULL;
ALTER TABLE posts ADD COLUMN status VARCHAR(255) NOT NULL;
ALTER TABLE posts ADD COLUMN user_id UUID NOT NULL;
ALTER TABLE posts ADD CONSTRAINT posts_users_fk FOREIGN KEY (user_id) REFERENCES users(id);