CREATE TABLE posts (
	id int8 GENERATED ALWAYS AS IDENTITY NOT NULL,
	title varchar NOT NULL,
	description varchar NOT NULL,
	"content" text NOT NULL,
	CONSTRAINT posts_pk PRIMARY KEY (id)
);
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE posts ADD COLUMN publication_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD COLUMN modification_date TIMESTAMP DEFAULT NULL;
ALTER TABLE posts ADD COLUMN status VARCHAR(255) NOT NULL;
ALTER TABLE posts ADD COLUMN user_id UUID NOT NULL;
ALTER TABLE posts ADD CONSTRAINT posts_users_fk FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN refresh_hash_code VARCHAR(255) NOT NULL;
